spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

videocreator:
  rabbit:
    exchange: "links_exchange"
    queue: "file_links_queue"
    routing-key: "links_rk"

server:
  port: 8084