voiceover:
  selenium:
    firefox-profile-path: "C:\\Users\\Dmitrii\\AppData\\Roaming\\Mozilla\\Firefox\\Profiles\\jawq71tv.default-release"
    download-dir: "D:\\rabbitConsumerFiles"

  site:
    url: "https://sintezator-rechi.ru/"
    voice: "Филипп"
    speed: "1.2"
    initial-wait-seconds: 10
    retry-wait-seconds: 10

  output:
    exchange: "links_exchange"
    routing-key: "links_rk"